name: Deploy to Production Test

on:
  push:
    branches: [ "test" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server (Upload Files)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "./*"
          target: "/var/www/html/Production_Test"
          rm: false
          strip_components: 0

      - name: Execute Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /var/www/html/Production_Test
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
