name: Deploy to Production Test

on:
  push:
    branches: [ "test" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Deployment Archive
        run: |
          tar -czf /tmp/deploy.tar.gz --exclude='.git' --exclude='.github' --exclude='node_modules' --exclude='vendor' .
          mv /tmp/deploy.tar.gz .

      - name: Deploy Archive to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "deploy.tar.gz"
          target: "/var/www/html/Production_Test"

      - name: Extract Archive and Execute Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /var/www/html/Production_Test
            tar -xzf deploy.tar.gz
            rm deploy.tar.gz
            mkdir -p storage/framework/{sessions,views,cache}
            mkdir -p storage/temp/mpdf
            sudo chmod -R 777 storage bootstrap/cache
            php artisan migrate --force
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
