name: Deploy to Production Test

on:
  push:
    branches: [ "test" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/var/www/html/Production_Test"
          EXCLUDE: "/dist/, /node_modules/, /vendor/, .git/, .github/"
          SCRIPT_AFTER: |
            cd /var/www/html/Production_Test
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
